In [1]:
import os
import numpy as np

import pandas as pd

In [13]:
data = pd.read_csv("./avatars_echOvid_train_X.csv")

data.head


<bound method NDFrame.head of       id                  Nom du centre  age      Sexe  \
0      1            Paris-APHP - Cochin   91  Masculin   
1    109        Paris-APHP - Hotel Dieu   45   Feminin   
2     46        Melun - CH Marc Jacquet   76   Feminin   
3    247        Paris-APHP - Hotel Dieu   55   Feminin   
4    195        Paris-APHP - Hotel Dieu   42   Feminin   
..   ...                            ...  ...       ...   
257  218            Paris-APHP - Cochin   34  Masculin   
258  199        Melun - CH Marc Jacquet   58   Feminin   
259  117            Paris-APHP - Cochin   45   Feminin   
260  201            Paris-APHP - Cochin   46   Feminin   
261   69  Creteil - APHP - Henri Mondor   79   Feminin   

    Lieu de provenance du patient             Echographiste Tabagisme actif  \
0                        Domicile     Forme pour l'epidemie             Non   
1                        Domicile  Experience d'echographie             Non   
2                           EHPAD  E

In [29]:
data.dtypes

id                                                                            int64
Nom du centre                                                                object
age                                                                           int64
Sexe                                                                         object
Lieu de provenance du patient                                                object
Echographiste                                                                object
Tabagisme actif                                                              object
BPCO                                                                         object
Asthme                                                                       object
Autre antecedent respiratoire                                                object
Hypertension arterielle                                                      object
Cardiopathie ischemique                                                     

In [80]:
feature_cols = ['Zone anterieure droite bas', 'Zone anterieure droite haut','Zone anterieure gauche bas', 'Zone anterieure gauche haut', 'Zone posterieure droite bas', 'Zone posterieure droite haut','Zone posterieure gauche bas', 'Zone posterieure gauche haut']

display(data[feature_cols])
X =data[feature_cols].apply(lambda value: value.map(lambda x: int(x[-1])))


y = data['Outcome J28']

Zone anterieure droite bas Zone anterieure droite haut  \
0                      Stade 2                     Stade 2   
1                      Stade 1                     Stade 0   
2                      Stade 1                     Stade 0   
3                      Stade 0                     Stade 0   
4                      Stade 0                     Stade 0   
..                         ...                         ...   
257                    Stade 0                     Stade 0   
258                    Stade 1                     Stade 1   
259                    Stade 0                     Stade 0   
260                    Stade 0                     Stade 0   
261                    Stade 1                     Stade 2   

    Zone anterieure gauche bas Zone anterieure gauche haut  \
0                      Stade 2                     Stade 1   
1                      Stade 0                     Stade 0   
2                      Stade 0                     Stade 1   
3                      Stade 0                     Stade 0   
4                      Stade 0                     Stade 0   
..                         ...                         ...   
257                    Stade 0                     Stade 0   
258                    Stade 0                     Stade 0   
259                    Stade 0                     Stade 0   
260                    Stade 0                     Stade 0   
261                    Stade 1                     Stade 2   

    Zone posterieure droite bas Zone posterieure droite haut  \
0                       Stade 2                      Stade 2   
1                       Stade 0                      Stade 0   
2                       Stade 2                      Stade 1   
3                       Stade 0                      Stade 0   
4                       Stade 0                      Stade 0   
..                          ...                          ...   
257                     Stade 0                      Stade 0   
258                     Stade 1                      Stade 1   
259                     Stade 0                      Stade 0   
260                     Stade 0                      Stade 0   
261                     Stade 1                      Stade 2   

    Zone posterieure gauche bas Zone posterieure gauche haut  
0                       Stade 2                      Stade 2  
1                       Stade 0                      Stade 0  
2                       Stade 2                      Stade 1  
3                       Stade 0                      Stade 0  
4                       Stade 0                      Stade 0  
..                          ...                          ...  
257                     Stade 0                      Stade 0  
258                     Stade 1                      Stade 0  
259                     Stade 0                      Stade 0  
260                     Stade 0                      Stade 0  
261                     Stade 2                      Stade 3  

[262 rows x 8 columns]

In [81]:
# split X and y into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [82]:
# train a logistic regression model on the training set
from sklearn.linear_model import LogisticRegression

# instantiate model
logreg = LogisticRegression()

# fit model
logreg.fit(X_train, y_train)

LogisticRegression()

In [83]:
# make class predictions for the testing set
y_pred_class = logreg.predict(X_test)

In [84]:

from sklearn import metrics
print(metrics.accuracy_score(y_test, y_pred_class))


0.7575757575757576


In [85]:
y_test.value_counts()


Back home              39
Hospitalization        23
Death                   2
Intensive care unit     2
Name: Outcome J28, dtype: int64

In [86]:
print(metrics.confusion_matrix(y_test, y_pred_class))


[[33  0  6  0]
 [ 0  0  0  2]
 [ 6  0 17  0]
 [ 0  0  2  0]]
