In [130]:
import os
import numpy as np

import pandas as pd

from datetime import datetime

In [143]:
df = pd.read_csv("./avatars_echOvid_train_X.csv")

In [144]:
print(list(df.head()))

['id', 'Nom du centre', 'age', 'Sexe', 'Lieu de provenance du patient', 'Echographiste', 'Tabagisme actif', 'BPCO', 'Asthme', 'Autre antecedent respiratoire', 'Hypertension arterielle', 'Cardiopathie ischemique', 'Cardiopathie rythmique', 'Diabete de type 1', 'Diabete de type 2', 'Diabetes', 'Cancer  hemopathie maligne', 'Demence', 'Statut immunodeprime', "AINS au long cours (dans le cadre d'une pathologie suivie)", 'AINS ponctuel recent (cadre des symptomatologies COVID-19 suspect avere)', 'Tension arterielle systolique (mmHg)', 'Tension arterielle diastolique (mmHg)', 'Frequence cardiaque (puls. min)', 'Frequence respiratoire (resp. min)', 'Temperature (Celsius)', 'Confusion', 'Saturation O2', 'Date de debut de la symptomatologie', 'Zone anterieure droite haut', 'Zone anterieure droite bas', 'Zone anterieure gauche haut', 'Zone anterieure gauche bas', 'Zone posterieure droite haut', 'Zone posterieure droite bas', 'Zone posterieure gauche haut', 'Zone posterieure gauche bas', 'Oxygeno

In [170]:
#feature_cols = []
stade_cols = [
    'Zone anterieure droite bas',
    'Zone anterieure droite haut',
    'Zone anterieure gauche bas',
    'Zone anterieure gauche haut',
    'Zone posterieure droite bas',
    'Zone posterieure droite haut',
    'Zone posterieure gauche bas',
    'Zone posterieure gauche haut',
]

boolean_cols = [
    'Tabagisme actif',
    'BPCO',
    'Asthme',
    'Autre antecedent respiratoire',
    'Hypertension arterielle',
    'Cardiopathie ischemique',
    'Cardiopathie rythmique',
    'Diabete de type 1',
    'Diabete de type 2',
    'Diabetes',
    'Cancer  hemopathie maligne',
    'Demence',
    'Statut immunodeprime',
    "AINS au long cours (dans le cadre d'une pathologie suivie)",
    'AINS ponctuel recent (cadre des symptomatologies COVID-19 suspect avere)',
    'Confusion',
]

int_cols = [
    'Tension arterielle diastolique (mmHg)',
    'Frequence cardiaque (puls. min)',
    'Frequence respiratoire (resp. min)',
    'Temperature (Celsius)',
    'Saturation O2',
]

unique_cols = [
    # 'Nom du centre',
    'age',
    'Sexe',
    'Lieu de provenance du patient',
    'Echographiste',
    'Tension arterielle systolique (mmHg)',
    'Date de debut de la symptomatologie',
    'Oxygenotherapie'
]

feature_cols = stade_cols + boolean_cols + unique_cols


In [171]:

data = df.copy()

def dt64_to_float(dt64):
  if type(dt64) is float and np.isnan(dt64):
    return .0 # np.nan
  try:
    time = datetime.strptime(dt64, '%Y-%m-%d')
    return time.timestamp()
  except Exception as e:
    print(dt64)
    print(e)
  return dt64

# Change date from object to float
data['Date de debut de la symptomatologie'] = data['Date de debut de la symptomatologie'].map(dt64_to_float).to_numpy()

# Change option to int
data['Oxygenotherapie'] = data['Oxygenotherapie'].map({"Air ambiant": 1, "Moderee": 2, "Assistance respiratoire": 3, np.nan:0}).to_numpy()

# Change string to int
data['Sexe'] = data['Sexe'].map({"Masculin": 0, "Feminin": 1}).to_numpy()

# Change string to int
data['Lieu de provenance du patient'] = data['Lieu de provenance du patient'].map({"Domicile": 0, "EHPAD": 1, "Hopital": 2, "Autre": 3, np.nan:4}).to_numpy()

# Change option to int
data['Echographiste'] = data['Echographiste'].map({"Forme pour l'epidemie": 1, "Exprerience d'echographie": 2, "Expert": 3, np.nan:0}).to_numpy()


def convert(x):
  if x == 'Oui':
    return 1
  return 0

data[boolean_cols] = data[boolean_cols].apply(lambda value: value.map(lambda x: 1 if x == 'Oui' else 0))

# Change data from string "Stade X" to int X
data[stade_cols] = data[stade_cols].apply(lambda value: value.map(lambda x: int(x[-1]) if type(x) is str else x))


In [172]:
X =data[feature_cols]
display(X)


y = data['Outcome J28']

Zone anterieure droite bas  Zone anterieure droite haut  \
0                             2                            2   
1                             1                            0   
2                             1                            0   
3                             0                            0   
4                             0                            0   
..                          ...                          ...   
257                           0                            0   
258                           1                            1   
259                           0                            0   
260                           0                            0   
261                           1                            2   

     Zone anterieure gauche bas  Zone anterieure gauche haut  \
0                             2                            1   
1                             0                            0   
2                             0                            1   
3                             0                            0   
4                             0                            0   
..                          ...                          ...   
257                           0                            0   
258                           0                            0   
259                           0                            0   
260                           0                            0   
261                           1                            2   

     Zone posterieure droite bas  Zone posterieure droite haut  \
0                              2                             2   
1                              0                             0   
2                              2                             1   
3                              0                             0   
4                              0                             0   
..                           ...                           ...   
257                            0                             0   
258                            1                             1   
259                            0                             0   
260                            0                             0   
261                            1                             2   

     Zone posterieure gauche bas  Zone posterieure gauche haut  \
0                              2                             2   
1                              0                             0   
2                              2                             1   
3                              0                             0   
4                              0                             0   
..                           ...                           ...   
257                            0                             0   
258                            1                             0   
259                            0                             0   
260                            0                             0   
261                            2                             3   

     Tabagisme actif  BPCO  ...  \
0                  0     0  ...   
1                  0     0  ...   
2                  0     0  ...   
3                  1     0  ...   
4                  0     0  ...   
..               ...   ...  ...   
257                1     0  ...   
258                0     0  ...   
259                0     0  ...   
260                0     0  ...   
261                0     0  ...   

     AINS au long cours (dans le cadre d'une pathologie suivie)  \
0                                                    0            
1                                                    0            
2                                                    0            
3                                                    0            
4                                                    0            
..                                                 ...    

In [173]:
# split X and y into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [174]:
# train a logistic regression model on the training set
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

# instantiate model
logreg = RandomForestClassifier()

# fit model
logreg.fit(X_train, y_train)

ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

In [168]:
# make class predictions for the testing set
y_pred_class = logreg.predict(X_test)

In [169]:

from sklearn import metrics
print(metrics.accuracy_score(y_test, y_pred_class))

0.8333333333333334


In [99]:
y_test.value_counts()


Back home              39
Hospitalization        23
Death                   2
Intensive care unit     2
Name: Outcome J28, dtype: int64

In [77]:
print(metrics.confusion_matrix(y_test, y_pred_class))


[[34  0  5  0]
 [ 0  0  0  2]
 [ 3  0 20  0]
 [ 0  0  1  1]]


In [78]:
y_test

194          Back home
153    Hospitalization
145          Back home
8            Back home
111          Back home
            ...       
184          Back home
15     Hospitalization
178          Back home
96           Back home
18               Death
Name: Outcome J28, Length: 66, dtype: object

In [80]:
test_data = pd.read_csv("./avatars_echOvid_test_X.csv")

X_test =test_data[feature_cols].apply(lambda value: value.map(lambda x: int(x[-1])))

y_pred_class = logreg.predict(X_test)

result_dataFrame =pd.DataFrame({'id':test_data['id'],'prediction':y_pred_class})
result_dataFrame = result_dataFrame.set_index('id')

display(result_dataFrame)
result_dataFrame.to_csv("./result.csv", sep =';')


prediction
id                  
237        Back home
236        Back home
253        Back home
92         Back home
53   Hospitalization
..               ...
151  Hospitalization
39         Back home
313        Back home
134        Back home
105        Back home

[66 rows x 1 columns]