In [2]:
import os
import numpy as np

import pandas as pd

In [3]:
data = pd.read_csv("./avatars_echOvid_train_X.csv")

display(data)


id                  Nom du centre  age      Sexe  \
0      1            Paris-APHP - Cochin   91  Masculin   
1    109        Paris-APHP - Hotel Dieu   45   Feminin   
2     46        Melun - CH Marc Jacquet   76   Feminin   
3    247        Paris-APHP - Hotel Dieu   55   Feminin   
4    195        Paris-APHP - Hotel Dieu   42   Feminin   
..   ...                            ...  ...       ...   
257  218            Paris-APHP - Cochin   34  Masculin   
258  199        Melun - CH Marc Jacquet   58   Feminin   
259  117            Paris-APHP - Cochin   45   Feminin   
260  201            Paris-APHP - Cochin   46   Feminin   
261   69  Creteil - APHP - Henri Mondor   79   Feminin   

    Lieu de provenance du patient             Echographiste Tabagisme actif  \
0                        Domicile     Forme pour l'epidemie             Non   
1                        Domicile  Experience d'echographie             Non   
2                           EHPAD  Experience d'echographie             Non   
3                         Hopital  Experience d'echographie             Oui   
4                        Domicile  Experience d'echographie             Non   
..                            ...                       ...             ...   
257                      Domicile     Forme pour l'epidemie             Oui   
258                      Domicile  Experience d'echographie             Non   
259                      Domicile                    Expert             Non   
260                      Domicile                    Expert             Non   
261                      Domicile  Experience d'echographie             Non   

    BPCO Asthme Autre antecedent respiratoire  ...  \
0    Non    Non                           Non  ...   
1    Non    Non                           Non  ...   
2    Non    Non                           Non  ...   
3    Non    Non                           Non  ...   
4    Non    Non                           Non  ...   
..   ...    ...                           ...  ...   
257  Non    Non                           Non  ...   
258  Non    Non                           Non  ...   
259  Non    Non                           Non  ...   
260  Non    Non                           Non  ...   
261  Non    Non                           Non  ...   

    Zone anterieure droite haut Zone anterieure droite bas  \
0                       Stade 2                    Stade 2   
1                       Stade 0                    Stade 1   
2                       Stade 0                    Stade 1   
3                       Stade 0                    Stade 0   
4                       Stade 0                    Stade 0   
..                          ...                        ...   
257                     Stade 0                    Stade 0   
258                     Stade 1                    Stade 1   
259                     Stade 0                    Stade 0   
260                     Stade 0                    Stade 0   
261                     Stade 2                    Stade 1   

    Zone anterieure gauche haut Zone anterieure gauche bas  \
0                       Stade 1                    Stade 2   
1                       Stade 0                    Stade 0   
2                       Stade 1                    Stade 0   
3                       Stade 0                    Stade 0   
4                       Stade 0                    Stade 0   
..                          ...                        ...   
257                     Stade 0                    Stade 0   
258                     Stade 0                    Stade 0   
259                     Stade 0                    Stade 0   
260                     Stade 0                    Stade 0   
261                     Stade 2                    Stade 1   

    Zone posterieure droite haut Zone posterieure droite bas  \
0                        Stade 2                     Stade 2   
1                        Stade 0                     Stade 0   
2                        Stad

In [4]:
data.dtypes

id                                                                            int64
Nom du centre                                                                object
age                                                                           int64
Sexe                                                                         object
Lieu de provenance du patient                                                object
Echographiste                                                                object
Tabagisme actif                                                              object
BPCO                                                                         object
Asthme                                                                       object
Autre antecedent respiratoire                                                object
Hypertension arterielle                                                      object
Cardiopathie ischemique                                                     

In [5]:
#feature_cols = []
feature_cols = ['Zone anterieure droite bas', 'Zone anterieure droite haut','Zone anterieure gauche bas', 'Zone anterieure gauche haut', 'Zone posterieure droite bas', 'Zone posterieure droite haut','Zone posterieure gauche bas', 'Zone posterieure gauche haut', 'Date de debut de la symptomatologie', 'Diabetes']

def dt64_to_float(dt64):
  year = dt64.astype('M8[Y]')
  days = (dt64 - year).astype('timedelta64[D]')
  year_next = year + np.timedelta64(1, 'Y')
  days_of_year = (year_next.astype('M8[D]') - year.astype('M8[D]')).astype('timedelta64[D]')
  dt_float = 1970 + year.astype(float) + days / (days_of_year)
  return dt_float

data['Date de debut de la symptomatologie'] = dt64_to_float(data['Date de debut de la symptomatologie'].to_numpy())
x = data['date_float'].values

# Change date from object to datetime
#data['Date de debut de la symptomatologie'] = pd.to_datetime(data['Date de debut de la symptomatologie'])

def convert(x):
  ret_value = x
  if x == 'Oui':
    ret_value= 0
  elif x == 'Non':
    ret_value= 1
  elif type(x) == str and x.split(' ')[0] == 'Stade':
    ret_value= int(x[-1])
  return ret_value

display(data[feature_cols])
X =data[feature_cols].apply(lambda value: value.map(lambda x: convert(x)))
display(X)


y = data['Outcome J28']

ValueError: Could not convert object to NumPy datetime

In [139]:
# split X and y into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [140]:
# train a logistic regression model on the training set
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

# instantiate model
logreg = RandomForestClassifier()

# fit model
logreg.fit(X_train, y_train)

ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

In [73]:
# make class predictions for the testing set
y_pred_class = logreg.predict(X_test)

In [74]:

from sklearn import metrics
print(metrics.accuracy_score(y_test, y_pred_class))

0.8333333333333334


In [76]:
y_test.value_counts()


Back home              39
Hospitalization        23
Death                   2
Intensive care unit     2
Name: Outcome J28, dtype: int64

In [77]:
print(metrics.confusion_matrix(y_test, y_pred_class))


[[34  0  5  0]
 [ 0  0  0  2]
 [ 3  0 20  0]
 [ 0  0  1  1]]


In [78]:
y_test

194          Back home
153    Hospitalization
145          Back home
8            Back home
111          Back home
            ...       
184          Back home
15     Hospitalization
178          Back home
96           Back home
18               Death
Name: Outcome J28, Length: 66, dtype: object

In [80]:
test_data = pd.read_csv("./avatars_echOvid_test_X.csv")

X_test =test_data[feature_cols].apply(lambda value: value.map(lambda x: int(x[-1])))

y_pred_class = logreg.predict(X_test)

result_dataFrame =pd.DataFrame({'id':test_data['id'],'prediction':y_pred_class})
result_dataFrame = result_dataFrame.set_index('id')

display(result_dataFrame)
result_dataFrame.to_csv("./result.csv", sep =';')


prediction
id                  
237        Back home
236        Back home
253        Back home
92         Back home
53   Hospitalization
..               ...
151  Hospitalization
39         Back home
313        Back home
134        Back home
105        Back home

[66 rows x 1 columns]